### PR TITLE
Status

### PR DESCRIPTION
**Pull request by KIngSimeone**

### CODE REVIEW

**Review by DeeMATT — APPROVED** [review]

**Comment by DeeMATT** [comment]
@KIngSimeone @bencipher 

Kindly help with resolving the conflicts. Thanks

**Comment by KIngSimeone** [comment]
> Kindly help with resolving the conflicts. Thanks

@DeeMATT its been resolved here, thanks

**Comment by DeeMATT** [comment]
@bencipher This one has conflict as a result of the other merge request that I just approved

**Comment by KIngSimeone** [comment]
Resolved @DeeMATT

**Comment by bencipher** [comment]
> @KIngSimeone @bencipher
> 
> Kindly help with resolving the conflicts. Thanks

What conflict, but I didn't work on your branch

**Pull request merged**
